import "../models/destination.dart";

class DestinationMedia {
  final String url;
  final String attribution;

  const DestinationMedia({
    required this.url,
    required this.attribution,
  });
}

/// Verified location-specific fallbacks for records whose local image cannot
/// decode on a target platform. These URLs point to Wikimedia Commons files;
/// each entry keeps the photographer and license visible to the UI.
///
/// GENERATED by scripts/sync_destination_media.py from
/// backend/data/destinations.json. Edit the data, then re-run the script.
/// Hand-editing this map is how it drifted out of sync with the data and
/// ended up holding an id that no longer existed and a URL that 404s.
const verifiedDestinationMedia = <String, DestinationMedia>{
  "dest-yao-001": DestinationMedia(
    url:
        "https://upload.wikimedia.org/wikipedia/commons/7/75/Yaounde_from_Febe.jpg",
    attribution: "Emmanuel Taquet — Wikimedia Commons, CC BY-SA 3.0",
  ),
  "dest-yao-002": DestinationMedia(
    url:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Monument_Reunification_4.JPG/1280px-Monument_Reunification_4.JPG",
    attribution: "Steve Mvondo — Wikimedia Commons, CC BY-SA 3.0",
  ),
  "dest-yao-003": DestinationMedia(
    url:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Mus%C3%A9e_national_de_Yaound%C3%A9_Cameroun.jpg/1280px-Mus%C3%A9e_national_de_Yaound%C3%A9_Cameroun.jpg",
    attribution: "Manuella sali — Wikimedia Commons, CC BY-SA 4.0",
  ),
  "dest-yao-004": DestinationMedia(
    url:
        "https://upload.wikimedia.org/wikipedia/commons/7/75/Yaounde_from_Febe.jpg",
    attribution: "Emmanuel Taquet — Wikimedia Commons, CC BY-SA 3.0",
  ),
  "dest-yao-007": DestinationMedia(
    url:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Mvog-Betsi_Zoo-Botanical_Park.jpg/1280px-Mvog-Betsi_Zoo-Botanical_Park.jpg",
    attribution: "Eleazar — Wikimedia Commons, CC BY-SA 3.0",
  ),
  "dest-yao-008": DestinationMedia(
    url:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Bastos_under_the_moon.jpg/1280px-Bastos_under_the_moon.jpg",
    attribution: "Shaowu Fan — Wikimedia Commons, CC BY 3.0",
  ),
  "dest-cmr-001": DestinationMedia(
    url:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Mount_Cameroon.jpg/1280px-Mount_Cameroon.jpg",
    attribution: "Daina — Wikimedia Commons, CC BY-SA 3.0",
  ),
  "dest-cmr-002": DestinationMedia(
    url:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Limbe_Botanic_Garden.jpg/1280px-Limbe_Botanic_Garden.jpg",
    attribution: "Awah Nadege — Wikimedia Commons, CC BY-SA 4.0",
  ),
  "dest-cmr-003": DestinationMedia(
    url:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Chutes_de_la_Lob%C3%A9_2.JPG/1280px-Chutes_de_la_Lob%C3%A9_2.JPG",
    attribution: "Aseret Zardep — Wikimedia Commons, CC BY-SA 4.0",
  ),
  "dest-cmr-004": DestinationMedia(
    url:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Ekom_falls.jpg/1280px-Ekom_falls.jpg",
    attribution: "UJung — Wikimedia Commons, CC BY-SA 3.0",
  ),
  "dest-cmr-005": DestinationMedia(
    url:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Waza-NP-Elephant.jpg/1280px-Waza-NP-Elephant.jpg",
    attribution: "Albert Backer — Wikimedia Commons, CC BY-SA 3.0",
  ),
  "dest-cmr-006": DestinationMedia(
    url:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/The_Sultans_Palace%2C_Foumban.jpg/1280px-The_Sultans_Palace%2C_Foumban.jpg",
    attribution: "Elin — Wikimedia Commons, CC BY 2.0",
  ),
};

DestinationMedia? mediaFallbackFor(Destination destination) =>
    verifiedDestinationMedia[destination.id];
