"""Regenerate the Dart fallback media map from the verified destinations data.

``destination_media.dart`` is the last line of defence: it is what the UI
reaches for when a bundled asset fails to decode on some platform. Hand-
maintaining it let two faults in — an entry for ``dest-yao-010``, a record
that no longer exists, and a URL for the Reunification Monument that Commons
has since deleted and now answers 404.

Generating it from ``destinations.json`` means the two can no longer disagree.
Only records whose attribution has been verified are emitted; an entry with
"unverified" in its credit would be a fallback we cannot stand behind.
"""

import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DATA = REPO / "backend/data/destinations.json"
DART = REPO / "frontend/lib/utils/destination_media.dart"

HEADER = '''import "../models/destination.dart";

class DestinationMedia {
  final String url;
  final String attribution;

  const DestinationMedia({
    required this.url,
    required this.attribution,
  });
}

/// Verified location-specific fallbacks for records whose local image cannot
/// decode on a target platform. These URLs point to Wikimedia Commons files;
/// each entry keeps the photographer and license visible to the UI.
///
/// GENERATED by scripts/sync_destination_media.py from
/// backend/data/destinations.json. Edit the data, then re-run the script.
/// Hand-editing this map is how it drifted out of sync with the data and
/// ended up holding an id that no longer existed and a URL that 404s.
const verifiedDestinationMedia = <String, DestinationMedia>{
'''

FOOTER = '''};

DestinationMedia? mediaFallbackFor(Destination destination) =>
    verifiedDestinationMedia[destination.id];
'''


def dart_string(value: str) -> str:
    """Escape a Python string for embedding in Dart double quotes."""
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("$", r"\$")


def main() -> int:
    raw = json.loads(DATA.read_text(encoding="utf-8"))
    records = raw if isinstance(raw, list) else raw.get("destinations", raw)

    entries = []
    for record in records:
        url = (record.get("image_url") or "").strip()
        attribution = (record.get("image_attribution") or "").strip()
        if not url or not attribution:
            continue
        if "unverified" in attribution.lower():
            continue
        entries.append((record["id"], url, attribution))

    body = []
    for identifier, url, attribution in entries:
        body.append(f'  "{identifier}": DestinationMedia(\n')
        body.append(f'    url:\n        "{dart_string(url)}",\n')
        body.append(f'    attribution: "{dart_string(attribution)}",\n')
        body.append("  ),\n")

    DART.write_text(HEADER + "".join(body) + FOOTER, encoding="utf-8")
    print(f"wrote {DART.relative_to(REPO)} with {len(entries)} verified entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
